version: "2"
services:
  ob_mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openboxes
      MYSQL_USER: openboxes
      MYSQL_PASSWORD: openboxes
    volumes:
      - openboxes/openboxes-mysql.cnf:/etc/mysql/conf.d/openboxes-mysql.cnf
    ports:
      - "3306:3306"
    networks:
      openboxes:
        aliases:
          - mysql
          
          
  ob_grails:
    build: ./grails-java7
    command: sh /root/openboxes-run.sh
    ports:
      - "8080:8080"
    volumes:
      - openboxes/openboxes-config.properties:/root/.grails/openboxes-config.properties
      - openboxes/openboxes-setenv.sh:/usr/share/tomcat7/bin/setenv.sh
      - openboxes/openboxes-run.sh:/root/openboxes-run.sh
      - openboxes:/app
    depends_on:
      - db
    networks:
      openboxes:
        aliases:
          - grails

networks:
  glpi-network:
    driver: bridge
